name: Test

on: push

jobs:
  if_merged:
    name: Create a new release of the Compendium
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract version from module.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version module.json -r'

      - name: Creation new version (Major) 🏷️
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.3
        with:
          current-version: ${{ steps.version.outputs.value }}
          version-fragment: 'major'

      - name: Update module.json version
        uses: jossef/action-set-json-field@v2
        with:
          file: module.json
          field: version
          value: ${{ steps.bump_version.outputs.next-version }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated version
          commit_user_name: Il Regno di Wagham
          commit_user_email: info@wagham.it